### ISSUE TITLE
No device detected when trying hip samples

### ISSUE THREAD

**Issue by SandboChang** [ROCm-Developer-Tools/HIP#2157]
Hi, 

With a system using AMD Threadripper 1950X,
I am trying to use my GPU, Radeon VII, on ubuntu 20.04.1 server as a VM under Proxmox. I was able to pass the GPU into the VM. To verify:

running
`/opt/rocm/bin/rocminfo`
```
ROCk module is loaded
Able to open /dev/kfd read-write
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen Threadripper 1950X 16-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen Threadripper 1950X 16-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      65536(0x10000) KB                  
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    49342116(0x2f0e6a4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    49342116(0x2f0e6a4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx906                             
  Uuid:                    GPU-ec0678e172fd5d72               
  Marketing Name:          Vega 20 [Radeon VII]               
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26287(0x66af)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1801                               
  BDFID:                   256                                
  Internal Node ID:        1                                  
  Compute Unit:            60                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx906          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done *** 
```

running 
```/opt/rocm/bin/hipconfig --full```

```
HIP version  : 3.7.20315-077bcfa0

== hipconfig
HIP_PATH     : /opt/rocm-3.7.0/hip
ROCM_PATH    : /opt/rocm-3.7.0
HIP_COMPILER : clang
HIP_PLATFORM : hcc
HIP_RUNTIME  : ROCclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=  -I/opt/rocm-3.7.0/hip/include -I/opt/rocm-3.7.0/llvm/bin/../lib/clang/11.0.0 -I/opt/rocm-3.7.0/hsa/include -D__HIP_ROCclr__

== hip-clang
HSA_PATH         : /opt/rocm-3.7.0/hsa
HIP_CLANG_PATH   : /opt/rocm-3.7.0/llvm/bin
clang version 11.0.0 (/src/external/llvm-project/clang ee4e4ebbadcc8ea14ce99e34ed31ab31e94827ac)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-3.7.0/llvm/bin
LLVM (http://llvm.org/):
  LLVM version 11.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags : -D__HIP_ROCclr__ -std=c++11 -isystem /opt/rocm-3.7.0/llvm/lib/clang/11.0.0/include/.. -isystem /opt/rocm-3.7.0/hsa/include -D__HIP_ROCclr__ -isystem /opt/rocm-3.7.0/hip/include -D__HIP_ARCH_GFX906__=1  -O3
hip-clang-ldflags  :  -L/opt/rocm-3.7.0/hip/lib -O3 -lgcc_s -lgcc -lpthread -lm

=== Environment Variables
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

== Linux Kernel
Hostname     : csns
Linux csns 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

However, then with my account under the group video,
when trying the bit_extract sample by executing `./bit_extract`
1. without sudo
`error: 'hipErrorNoDevice'(100) at bit_extract.cpp:58
`
2. with sudo
```
/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:92: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Aborted
```

Finally, I checked the path
```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin
```

Is VM compatible with ROCm? Or may be I am missing something from the installation?
Any ideas are appreciated.

**Comment by powderluv** [comment]
did you resolve this issue ? I am also getting the hipErrorNoDevice though rocminfo shows both cpu and gpu

**Comment by PaulKarlshoeferBULL** [comment]
Me, too. Is there a solution?

**Comment by SandboChang** [comment]
Unfortunately not really, I actually just setup another Proxmox system with the latest software version, plus using ROCm 4.0.1.
I am being hit with the same error as I am trying to use cupy with RVII.

**Comment by PaulKarlshoeferBULL** [comment]
I noticed that I was missing some rights. In my case, I was not part of a Linux "group" which was the only group allowed to operate on the device. After being added to the group, I also had to recompile all sources compiled which hipcc, etc. now it works nicely.

**Comment by SandboChang** [comment]
> 
> 
> I noticed that I was missing some rights. In my case, I was not part of a Linux "group" which was the only group allowed to operate on the device. After being added to the group, I also had to recompile all sources compiled which hipcc, etc. now it works nicely.

May I know which group was it? I have already added myself into video, but it did not help.

**Comment by xuhuisheng** [comment]
Before Ubuntu-20.04 (not included 20.04), we need group 'video'.
After Ubuntu-20.04 (include 20.04), we need group 'render'.

You can check kfd group by `ls -l /dev/kfd`.

```
work@fc00e52d30c9:~$ ls -l /dev/kfd
crw-rw-rw- 1 root render 239, 0 Mar 15 18:09 /dev/kfd

```

**Comment by SandboChang** [comment]
> Before Ubuntu-20.04 (not included 20.04), we need group 'video'.
> After Ubuntu-20.04 (include 20.04), we need group 'render'.
> 
> You can check kfd group by `ls -l /dev/kfd`.
> 
> ```
> work@fc00e52d30c9:~$ ls -l /dev/kfd
> crw-rw-rw- 1 root render 239, 0 Mar 15 18:09 /dev/kfd
> ```

Thanks a lot!
I haven't tried but this is likely why. 
I didn't read the wiki in full I guess, as I kind of remember the steps lol

**Comment by PaulKarlshoeferBULL** [comment]
> > I noticed that I was missing some rights. In my case, I was not part of a Linux "group" which was the only group allowed to operate on the device. After being added to the group, I also had to recompile all sources compiled which hipcc, etc. now it works nicely.
> 
> May I know which group was it? I have already added myself into video, but it did not help.

video, yes

**Comment by SandboChang** [comment]
Solved by adding the user to the group "video" and "render", the latter is required in new ROCm implementations.
