### ISSUE TITLE
Get hipErrorNoBinaryForGpu when running the HIP Sample

### ISSUE THREAD

**Issue by tomac204** [ROCm-Developer-Tools/HIP#2166]
I tried to follow the instructions on page https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html# to compile and install the basic rocm3.7 compnents manually, kernel driver has already been installed and loaded successfully.

HIP ROCm-CompilerSupport rocminfo ROCR-Runtime ROCm-Device-Libs ROCT-Thunk-Interface ROCm-OpenCL-Runtime ROCclr llvm-project

When I ran HIP/samples/0_Intro/square example, I got following output:
LoadLib(libhsa-amd-aqlprofile64.so) failed: libhsa-amd-aqlprofile64.so: cannot open shared object file: No such file or directory
/work/HIP/rocclr/hip_code_object.cpp:92: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Aborted (core dumped)

Any advice for these errors?
Which project/repository will generate libhsa-amd-aqlprofile64.so?
How to fix hipErrorNoBinaryForGpu?

the outputs of rocminfo and hipconfig are in the attachment.
[hipconfig.txt](https://github.com/ROCm-Developer-Tools/HIP/files/5192401/hipconfig.txt)
[rocminfo.txt](https://github.com/ROCm-Developer-Tools/HIP/files/5192402/rocminfo.txt)

**Comment by cmal** [comment]
same problem.

**Comment by passingglance** [comment]
I've also encountered the same problem.  I have a couple insights to add.

As far as I can tell, the libhsa-amd-aqlprofile64.so is only available as a binary. I found it on http://repo.radeon.com/   In particular, I grabbed an RPM and extracted it. (http://repo.radeon.com/rocm/centos8/3.9.1/hsa-amd-aqlprofile3.9.1-1.0.0-Linux.rpm)

As for hipErrorNoBinaryForGpu, I found the target name is wrong in my binary.  I decorated hip_code_object.cpp with some print statements and found this:
`device_names:
    gfx900
target:
    -gfx900 (hip-amdgcn-amd-amdhsa--gfx900)
/home/jerry/local/rocm/src/HIP-3.9.x/rocclr/hip_code_object.cpp:125: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Aborted`

Not sure why the double dash "--" at the end of the triple. Possibly the target wasn't specified correctly when building llvm or lld?

**Comment by passingglance** [comment]
I've tracked down the cause of why I'm getting hipErrorNoBinaryForGpu.  At [rocclr/hip_code_object.hpp](https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-3.10.x/rocclr/hip_code_object.hpp):26, HIP_AMDGCN_AMDHSA_TRIPLE is defined as "hip-amdgcn-amd-andhsa", without a trailing dash.  The define just below for HCC_AMDGCN_AMDHSA_TRIPLE does have a trailing slash.
Then, in [rocclr/hip_code_object.cpp](https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-3.10.x/rocclr/hip_code_object.cpp) those defines are used to match and the string length is used as an offset used to extract the target name. The full target name in the binary is "hip-amdgcn-amd-amdhsa--gfx900", so without the trailing dash as noted above, the extracted target name ends up "-gfx900", with an extra leading dash. This fails to match the requested device_name of "gfx900", and with no match, the error is thrown.

**Comment by Nop287** [comment]
I am getting the same error after a clean install of ROCm and tensorflow on a CentOS 8.2. When trying tensorflow examples I get:
/data/jenkins_workspace/centos_pipeline_job_8.1_rel-3.10/rocm-rel-3.10/rocm-3.10-27-20201120/8.1/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
My GPU in rocminfo is "ahsa-mdgcn-amd-amd-gfx803"
Will this be fixed anytime? My C / C++ skills are a bit rusty and I do not intend to rebuild the libraries. I just want to use tensorflow from Python. I have tried this many times using different OS versions for both Ubuntu and CentOS and different ROCm versions and did not get it to run a single time. Does anybody at AMD really care about tensorflow?

**Comment by Nop287** [comment]
As an addition: After installing Development Tools on CentOS I can make the square example for HIP without problems:
info: running on device Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
info: allocate host mem (  7.63 MB)
info: allocate device mem (  7.63 MB)
info: copy Host2Device
info: launch 'vector_square' kernel
info: copy Device2Host
info: check result
PASSED!
So perhaps hip_code_object.hpp is not the problem but the yet again the compiled version of tensorflow, at least for me?

**Comment by marcusnchow** [comment]
Is this still an issue for people? I am build the rocm stack from source (3.10.0) on a gfx906. I'm getting an error when trying to run gpu_burn

HIP/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")

**Comment by passingglance** [comment]
I can't offer much but to say that I was getting this same error, and after a few tries of wiping out the install and rebuilding everything again, I got it working.  I tried to be systematic about setting environment variables and checking all the build parameters (cmake -LA).  Anything that didn't look right, I explicitly set it. I also removed every vestige of a prior install by distro packages.

Unfortunately I don't know what of this fixed it. I'm certain it's something going wrong in the build process that leads to this error.  I'll see if I can get the error to happen again and figure out it out.

**Comment by marcusnchow** [comment]
Thanks, I've rebuilt a couple of times now with no avail. What environment variables did you end up setting? I was thinking it might be AMDGPU_TARGETS but that seems to be set properly for me

**Comment by passingglance** [comment]
I first built and installed llvm-project-rocm (with ROCm-Device-Libs, as shown in the Device-Libs README.md).  After that, update my env.  I'm installing it at $HOME/rocm instead of the default.

export ROCM_PATH=$HOME/rocm
export HSA_PATH=$ROCM_PATH
export HIP_PATH=$ROCM_PATH
export DEVICE_LIB_PATH=$ROCM_PATH/amdgcn/bitcode
export PATH=$HOME/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$ROCM_PATH/bin:$ROCM_PATH/lib/clang/12.0.0/bin
export LD_LIBRARY_PATH=$ROCM_PATH/lib:$ROCM_PATH/lib64

My default PATH includes the system LLVM install (/usr/lib/llvm/11/bin), so I'm explicitly setting it. After installing llvm-project-rocm and setting $PATH, do a which clang to make sure the shell is finding the newly installed clang, not the system clang. I also found a few files installed in $ROCM_PATH/lib64, but hipconfig only includes lib in the search path.

Lastly, I didn't add this to my rocm shell setup, but I had also set this when building ROCclr.

export HIP_CLANG_PATH=$ROCM_PATH

That's what I find in my scripts. If that's not enough, I'll post my cmake invocation scripts somewhere to show the parameters I passed.

**Comment by xuhuisheng** [comment]
@passingglance which branch are you used?
dont use develop or master branch, these branches may contain unstable source code. please switch to related branch or tag, like rocm-4.0.x or rocm-4.0.0.

**Comment by passingglance** [comment]
@xuhuisheng I had first built ROCm using rocm-3.9.x, and moved to rocm-3.10.x somewhere in my flailing to get it working.  I'm not getting the error reported in this issue anymore, but my first couple tries building ROCm from source I did get the error when trying to run some example code.  Between getting the error and getting a good build, I changed too much on my system and build setup to know what resolved it.

My best recollection now is I found the /tmp/vectorAdd-gfx900-e635fb.o generated by the first clang-12 call hipcc makes did not actually have a vectorAdd symbol in it.  If I run the first command manually now with my good build, I see thee _Z15vectorAdd... symbols in the object file.

**Comment by xuhuisheng** [comment]
@passingglance
It is weird that gfx900 met this issue. I guess maybe you modified AMDGPU_TARGETS, and remove gfx900 by mistake.

gfx803 always met this issue after ROCm-3.7+, please refer this issue: https://github.com/RadeonOpenCompute/ROCm/issues/1265

**Comment by marcusnchow** [comment]
So I got my build to work, I think it had to do with me using the wrong llvm repo. This is completely off topic from this issue but, can someone enlighten my one what the difference between these three llvm-projects amd's got going on
[ROCm-Developer-Tools/llvm-project](https://github.com/ROCm-Developer-Tools/llvm-project)
[RadeonOpenCompute/llvm-project](https://github.com/RadeonOpenCompute/llvm-project)
[ROCm-Developer-Tools/amd-llvm-project](https://github.com/ROCm-Developer-Tools/amd-llvm-project)

I switched to RadeonOpenCompute/llvm-project and that got rid of the error for me

**Comment by SarbojitAMD** [comment]
Closing the ticket, feel free to open in case you still see the issue.
